#!/usr/bin/env python3
"""
Generate the game's surface textures with sdxl-turbo, then make them usable.

Upgraded from sd-turbo (SD2.1-distilled, ~530M UNet, native 512px) to
sdxl-turbo (SDXL-distilled, ~2.6B UNet + dual text encoders, native 1024px).
Benchmarked on this machine first (see bench_sdxl.py): ~50s one-time model
load, ~18s per image at 2 steps, ~11GB peak RSS — comfortably inside a 15GB
box and a couple of minutes total for the whole set, for a real jump in
per-pixel detail over the SD2.1 model. That detail is the point: distilled
turbo models are still small compared to a full multi-step pipeline, so the
gap between "the fast CPU-friendly model" and "the good model" is mostly
parameter count, and SDXL has roughly 5x sd-turbo's.

A diffusion model does not produce a tiling texture, and a distilled model
also is not reliably supersampled at its input resolution. So each image goes
through four steps that matter more than the prompt:

  1. **Render oversized.** Generated at 768px and Lanczos-downsampled to 512
     at the very end, after every pixel-domain operation below. This is
     ordinary supersampling: it costs one resize and buys back the aliasing a
     single-step model leaves in fine grain (gravel, brush strokes, weave).

  2. **Seamless wrap.** The image is blended with its three half-offset copies
     under cosine weights that share the tile's period. Each copy is weighted
     to zero exactly where its own seam falls, and periodic weights make the
     result continuous across the tile boundary by construction.

  3. **Flatten the lighting.** Diffusion bakes light and shadow into the image.
     Baked light on a surface that the engine is also lighting reads as dirt
     that moves wrongly, so a heavy blur of the image is divided out, leaving
     the grain and discarding the illumination.

  4. **Desaturate towards the palette.** The city runs a strict green/blue/
     purple script. A texture that arrives with its own colour opinion fights
     that, so albedo is pulled most of the way to greyscale and tinted in the
     engine instead.

Output is 512px JPEG at quality 80 — roughly 60-100KB each. That is a real
cost against a bundle that was previously 100% procedural, which is why the
set is kept to the surfaces actually seen close up and tiled: road, concrete,
metal trim, lounge decking, lounge cushions. Glossy car paint and low-poly
foliage stay procedural on purpose — a photographic map on a smooth painted
panel or on an icosahedron's default UVs would look worse, not better.

Each albedo also gets a `{name}_n.jpg` normal map, derived from its own
luminance with a Sobel filter (`make_normal`, below) — not generated by the
model. Real per-pixel surface relief under the engine's lighting is a bigger
visible jump than the albedo alone: the same road that used to shade as a
flat tinted plane now catches the key light on individual grains. See
make_normals.py to (re)derive normal maps for albedo that already exists on
disk, without paying for another sdxl-turbo run.
"""
import sys
from pathlib import Path

import numpy as np
from PIL import Image, ImageFilter

# torch/diffusers are only needed for the generation path (main(), below);
# importing them costs real seconds and pulls in a CPU inference stack, so
# they are imported lazily inside main() rather than at module scope. That
# keeps `from make_textures import make_normal` (used by make_normals.py to
# derive bump maps from *already generated* jpgs, with no model involved)
# fast and dependency-light.

MODEL = "stabilityai/sdxl-turbo"
GEN_SIZE = 768   # rendered resolution, before downsampling
OUT_SIZE = 512   # shipped resolution
STEPS = 2
OUT = Path("public/textures")

# Prompts are written for *flat, evenly lit, top-down* surfaces. Anything that
# invites composition — "a road", "a wall in a city" — produces a picture with
# perspective and a light source, which is useless as a tiling material.
TEXTURES = {
    "asphalt": (
        "flat overhead photograph of worn wet asphalt road surface, fine gravel "
        "aggregate, evenly lit, no shadows, no markings, no perspective, "
        "seamless texture, macro detail, 8k"
    ),
    "concrete": (
        "flat overhead photograph of raw poured concrete slab, subtle pitting "
        "and fine cracks, evenly lit, no shadows, no perspective, seamless "
        "texture, macro detail, 8k"
    ),
    "panel": (
        "flat overhead photograph of brushed dark metal panel, fine horizontal "
        "brush grain, subtle scratches, evenly lit, no shadows, no perspective, "
        "seamless texture, macro detail, 8k"
    ),
    "wood": (
        "flat overhead photograph of dark stained oak deck planking, fine wood "
        "grain, subtle weathering, evenly lit, no shadows, no perspective, "
        "seamless texture, macro detail, 8k"
    ),
    "fabric": (
        "flat overhead photograph of woven upholstery fabric, fine cross weave "
        "texture, soft lounge cushion material, evenly lit, no shadows, no "
        "perspective, seamless texture, macro detail, 8k"
    ),
}


def make_seamless(img: Image.Image) -> Image.Image:
    """
    Blend the image with its three half-offset copies under periodic weights.

    Each copy carries its discontinuity somewhere different: the original's is
    at the edges, the x-rolled copy's is down the middle vertically, and so on.
    The weights are cosine ramps with exactly the tile's period, so each copy
    is weighted to *zero* precisely where its own seam lies, and because the
    weights are periodic the result is continuous across the tile boundary by
    construction.

    An earlier version rolled the image and then faded back to the original
    towards the edges. That is inverted: it restores the original's mismatched
    edge exactly where the seam has to disappear, which is why a faint line ran
    down the middle of every tile.
    """
    a = np.asarray(img.convert("RGB"), dtype=np.float32)
    h, w, _ = a.shape

    rx = np.roll(a, w // 2, axis=1)
    ry = np.roll(a, h // 2, axis=0)
    rxy = np.roll(rx, h // 2, axis=0)

    # 0 at the tile edge, 1 at the centre, and periodic with the tile.
    wx = (0.5 - 0.5 * np.cos(2 * np.pi * np.arange(w) / w))[None, :, None]
    wy = (0.5 - 0.5 * np.cos(2 * np.pi * np.arange(h) / h))[:, None, None]

    out = (a * wx * wy
           + rx * (1 - wx) * wy
           + ry * wx * (1 - wy)
           + rxy * (1 - wx) * (1 - wy))

    # Averaging four copies flattens contrast; restore the original spread so
    # the grain does not turn to mush.
    out = (out - out.mean()) * (a.std() / max(out.std(), 1e-3)) + a.mean()
    return Image.fromarray(np.clip(out, 0, 255).astype(np.uint8))


def flatten_lighting(img: Image.Image, strength: float = 0.85) -> Image.Image:
    """Divide out a heavy blur, removing baked illumination but keeping grain."""
    a = np.asarray(img.convert("RGB"), dtype=np.float32)
    low = np.asarray(img.convert("RGB").filter(ImageFilter.GaussianBlur(28)),
                     dtype=np.float32)
    flat = a / np.maximum(low, 1.0) * low.mean()
    out = a * (1 - strength) + flat * strength
    return Image.fromarray(np.clip(out, 0, 255).astype(np.uint8))


def toward_grey(img: Image.Image, amount: float = 0.78) -> Image.Image:
    """Pull most of the way to greyscale so the engine's palette decides hue."""
    a = np.asarray(img.convert("RGB"), dtype=np.float32)
    lum = a @ np.array([0.2126, 0.7152, 0.0722], dtype=np.float32)
    out = a * (1 - amount) + lum[..., None] * amount
    # Re-centre so every texture arrives at a predictable mid grey; the material
    # colour supplies the actual value.
    out *= 128.0 / max(out.mean(), 1.0)
    return Image.fromarray(np.clip(out, 0, 255).astype(np.uint8))


def make_normal(img: Image.Image, strength: float = 2.2) -> Image.Image:
    """
    Derive a tangent-space normal map from albedo luminance with a Sobel
    filter. No model involved -- this is the classic bump-from-height trick,
    deterministic and fast, which is exactly why it belongs at the end of the
    albedo pipeline rather than as another diffusion prompt: asking a
    generative model for "a normal map of X" produces a plausible-looking
    purple image with no actual correspondence to X's real surface relief,
    while a filter over the *actual* generated grain is guaranteed to
    correspond to what is on screen.

    `strength` scales the height gradient before it is packed into XY; higher
    reads as deeper relief. Z is solved from X/Y so the vector stays unit
    length, which is what keeps specular highlights from swimming as the
    light direction changes.
    """
    lum = np.asarray(img.convert("L"), dtype=np.float32) / 255.0
    # Wrap at the edges (mode="wrap") rather than clamp, so the normal map
    # tiles exactly as seamlessly as the albedo it was derived from.
    gx = (np.roll(lum, -1, axis=1) - np.roll(lum, 1, axis=1)) * strength
    gy = (np.roll(lum, -1, axis=0) - np.roll(lum, 1, axis=0)) * strength

    nx, ny, nz = -gx, -gy, np.ones_like(lum)
    length = np.sqrt(nx * nx + ny * ny + nz * nz)
    nx, ny, nz = nx / length, ny / length, nz / length

    rgb = np.stack([
        (nx * 0.5 + 0.5) * 255,
        (ny * 0.5 + 0.5) * 255,
        (nz * 0.5 + 0.5) * 255,
    ], axis=-1)
    return Image.fromarray(np.clip(rgb, 0, 255).astype(np.uint8))


def main() -> int:
    import torch
    from diffusers import AutoPipelineForText2Image

    only = sys.argv[1] if len(sys.argv) > 1 else None
    OUT.mkdir(parents=True, exist_ok=True)

    print(f"loading {MODEL} on CPU...", flush=True)
    pipe = AutoPipelineForText2Image.from_pretrained(
        MODEL, torch_dtype=torch.float32, safety_checker=None
    ).to("cpu")
    pipe.set_progress_bar_config(disable=True)

    for name, prompt in TEXTURES.items():
        if only and only != name:
            continue
        print(f"  {name}...", flush=True)
        image = pipe(
            prompt=prompt,
            num_inference_steps=STEPS,
            guidance_scale=0.0,
            height=GEN_SIZE,
            width=GEN_SIZE,
        ).images[0]

        image = flatten_lighting(image)
        image = make_seamless(image)
        image = toward_grey(image)
        # Downsample last: every op above works in the pixel domain, so doing
        # this first would just make them operate on fewer samples. Doing it
        # last is what actually buys back the aliasing sdxl-turbo's 2-step
        # sampling leaves in fine grain.
        image = image.resize((OUT_SIZE, OUT_SIZE), Image.LANCZOS)

        path = OUT / f"{name}.jpg"
        image.save(path, quality=80, optimize=True)
        print(f"  -> {path} ({path.stat().st_size // 1024}KB)", flush=True)

        normal = make_normal(image)
        npath = OUT / f"{name}_n.jpg"
        normal.save(npath, quality=85, optimize=True)
        print(f"  -> {npath} ({npath.stat().st_size // 1024}KB)", flush=True)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
